name: Deployment

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: "16"

      - name: Setup pnpm
        run: |-
          corepack enable
          pnpm --version

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >>$GITHUB_OUTPUT

      - name: Cache pnpm modules
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.OS }}-pnpm-current-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-current

      - name: Install packages
        run: pnpm install

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382 # v3

      - name: Build
        run: pnpm run build
        env:
          RTE_BASE_URL: ${{ steps.pages.outputs.base_path }}
          RTE_TREE_URL: https://github.com/${{ github.repository }}/tree/${{ github.sha }}/
          RTE_BLOB_URL: https://github.com/${{ github.repository }}/blob/${{ github.sha }}/

      - name: Remove generated declaration files
        run: rm -r build/types

      - name: Upload artifact
        uses: actions/upload-pages-artifact@84bb4cd4b733d5c320c9c9cfbc354937524f4d64 # v1
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@9dbe3824824f8a1377b8e298bafde1a50ede43e5 # v2
