name: Validate renovate config

on:
  push:
    branches:
      - main
      - releases/**
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"
  pull_request:
    branches:
      - main
      - releases/**
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"

jobs:
  validate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Validate renovate config
        run: npx -y --package renovate -- renovate-config-validator
