name: Validate renovate config

on:
  push:
    branches:
      - main
      - releases/**
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"
  pull_request:
    branches:
      - main
      - releases/**
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"

jobs:
  validate-renovate-config:
    name: Validate renovate config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Validate renovate config
        run: npx -y --package renovate -- renovate-config-validator
