name: Validate renovate config

on:
  push:
    branches:
      - main
      - releases/**
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"
  pull_request:
    branches:
      - main
      - releases/**
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"

jobs:
  validate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Validate renovate config
        run: npx -y --package renovate -- renovate-config-validator
