name: Validate renovate config

on:
  push:
    branches:
      - main
      - releases/**
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"
  pull_request:
    branches:
      - main
      - releases/**
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"

jobs:
  validate-renovate-config:
    name: Validate renovate config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Validate renovate config
        run: npx -y --package renovate -- renovate-config-validator
