name: REUSE compliance

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  reuse-compliance:
    name: REUSE compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@e7a435374d26d54b324fa6699d8eafb076340dfd # v1.2.0
