name: REUSE compliance

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  reuse-compliance:
    name: REUSE compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@e7a435374d26d54b324fa6699d8eafb076340dfd # v1.2.0
